<?php
/**
 * Created by PhpStorm.
 * User: michael
 * Date: 5/13/15
 * Time: 18:32
 */

namespace App\DAO;


use App\DAO\base\CollectionBase;

class CacheDAO extends CollectionBase {
    public function __construct()
    {
        parent::__construct("caches"); // TODO: Change the autogenerated stub
    }


}