<?php
/**
 * Created by PhpStorm.
 * User: michael
 * Date: 4/23/15
 * Time: 15:05
 */

namespace App\DAO;

use App\DAO\base\CollectionBase;

class LeagueDAO extends CollectionBase{
    public function __construct()
    {
        parent::__construct("leagues"); // TODO: Change the autogenerated stub
    }
    public static function makeObject($reference_id,$code,$name,$website='',$color='') {
        $new_obj=parent::formatObject();
        $new_obj->reference_id=intval($reference_id);
        $new_obj->code=$code;
        $new_obj->name=$name;
        $new_obj->website=$website;
        $new_obj->color=$color;

        return $new_obj;
    }

}