<?php
/**
 * Created by PhpStorm.
 * User: Kudo Shinichi
 * Date: 5/8/2015
 * Time: 3:11 PM
 */
namespace App\DAO;

use App\DAO\base\CollectionBase;

class LogDAO extends CollectionBase {
    private static $instance;
    public static function getInstance()
    {
        if(self::$instance==null) {
            self::$instance=new LogDAO();
        }
        return self::$instance;
    }

    public function __construct()
    {
        parent::__construct("log"); // TODO: Change the autogenerated stub
    }

}
