<?php
/**
 * Created by PhpStorm.
 * User: michael
 * Date: 4/23/15
 * Time: 15:04
 */

namespace App\DAO;

use App\DAO\base\CollectionBase;

class OddDAO extends CollectionBase{
    public function __construct()
    {
        parent::__construct("odds"); // TODO: Change the autogenerated stub
    }
    private static $instance;
    public static function getInstance()
    {
        if(self::$instance==null) {
            self::$instance=new OddDAO();
        }
        return self::$instance;
    }
    public static function makeObject($match,$home,$h_draw,$g_draw,$away,$type) {
        $new_obj=parent::formatObject();
        $new_obj->match_id=$match->_id;
        $new_obj->time=$match->status==1?intval($match->time):-1;
        $new_obj->h_goal=$match->h_goal;
        $new_obj->g_goal=$match->g_goal;
        $new_obj->home=$home;
        $new_obj->draw=abs($h_draw);
        $new_obj->h_draw=$h_draw;
        $new_obj->g_draw=$g_draw;
        $new_obj->away=$away;
        $new_obj->type=$type;

        $md5_obj=clone $new_obj;
        unset($md5_obj->created_at);
        unset($md5_obj->updated_at);
        $new_obj->md5=md5(json_encode($md5_obj));

        return $new_obj;
    }

}