<?php
namespace App\DAO;

use App\DAO\base\CollectionBase;

class SupplierDAO extends CollectionBase {
    public function __construct()
    {
        parent::__construct("suppliers"); // TODO: Change the autogenerated stub
    }
}
