<?php
namespace App\DAO;

use App\DAO\base\CollectionBase;

class SupplierDAO extends CollectionBase {
    public function __construct()
    {
        parent::__construct("suppliers"); // TODO: Change the autogenerated stub
    }
    private static $instance;
    public static function getInstance()
    {
        if(self::$instance==null) {
            self::$instance=new SupplierDAO();
        }
        return self::$instance;
    }
}
