<?php
namespace App\DAO;

use App\DAO\base\CollectionBase;

class UserDAO extends CollectionBase {
    private static $instance;
    public static function getInstance()
    {
        if(self::$instance==null) {
            self::$instance=new UserDAO();
        }
        return self::$instance;
    }

    public function __construct()
    {
        parent::__construct("users"); // TODO: Change the autogenerated stub
    }

}
