<?php
/**
 * Created by PhpStorm.
 * User: michael
 * Date: 4/23/15
 * Time: 15:05
 */

namespace App\Models;

use App\Models\base\CollectionBase;

class Leagues extends CollectionBase{
    public function __construct()
    {
        parent::__construct("leagues"); // TODO: Change the autogenerated stub
    }

}