<?php
/**
 * Created by PhpStorm.
 * User: michael
 * Date: 4/23/15
 * Time: 15:03
 */

namespace App\Models;


use App\Models\base\CollectionBase;

class Matchs extends CollectionBase {
    public function __construct()
    {
        parent::__construct("matchs"); // TODO: Change the autogenerated stub
    }

}