<?php
/**
 * Created by PhpStorm.
 * User: michael
 * Date: 4/23/15
 * Time: 15:04
 */

namespace App\Models;

use App\Models\base\CollectionBase;

class Odds extends CollectionBase{
    public function __construct()
    {
        parent::__construct("odds"); // TODO: Change the autogenerated stub
    }
    public static function makeObject($match,$home,$draw,$away,$type) {
        $new_obj=parent::formatObject();
        $new_obj->match_id=$match->_id;
        $new_obj->time=$match->started==true?$match->time:-1;
        $new_obj->h_goal=$match->h_goal;
        $new_obj->g_goal=$match->g_goal;
        $new_obj->home=$home;
        $new_obj->draw=$draw;
        $new_obj->away=$away;
        $new_obj->type=$type;

        return $new_obj;
    }

}