<?php
/**
 * Created by PhpStorm.
 * User: michael
 * Date: 4/23/15
 * Time: 15:04
 */

namespace App\Models;

use App\Models\base\CollectionBase;

class Odds extends CollectionBase{
    public function __construct()
    {
        parent::__construct("odds"); // TODO: Change the autogenerated stub
    }

}