<?php
namespace App\Models;


use App\Models\base\CollectionBase;

class Rules extends CollectionBase {
    const TYPE_RULE = 'rule';
    const TYPE_CONDITON = 'condition';
    public function __construct()
    {
        parent::__construct("rules"); // TODO: Change the autogenerated stub
    }

}
