<?php
namespace App\Models;


use App\Libraries\Constants;
use App\Models\base\CollectionBase;

class Rules extends CollectionBase {
    public function __construct() {
        parent::__construct("rules"); // TODO: Change the autogenerated stub
    }

    public static function makeObject($params) {
        $rule = parent::formatObject();
        if(isset($params['type'])) {
            // Rules
            if($params['type'] == Constants::TYPE_RULE) {
                $conditionLeftData = explode(':', $params['condition_left']);
                $conditionRightData = explode(':', $params['condition_right']);
                $data['condition_left'] = array(
                    'id' => $conditionLeftData[0],
                    'name' => $params['condition_left_display'],
                    'type' => $conditionLeftData[1],
                );
                $data['condition_right'] = array(
                    'id' => $conditionRightData[0],
                    'name' => $params['condition_right_display'],
                    'type' => $conditionRightData[1],
                );

                $rule->condition_left = $data['condition_left'];
                $rule->condition_right = $data['condition_right'];
            } elseif($params['type'] == Constants::TYPE_CONDITION) {
                $rule->field = $params['field'];
                $rule->time = $params['time'];
                $rule->value = $params['value'];
                $rule->odd_type = $params['odd_type'];
            }
            $rule->name = $params['name'];
            $rule->operator = $params['operator'];
            $rule->description = $params['description'];
            $rule->type = $params['type'];

        }
        return $rule;
    }
}
