<?php
namespace App\Models;


use App\Models\base\CollectionBase;

class Rules extends CollectionBase {
    public function __construct()
    {
        parent::__construct("rules"); // TODO: Change the autogenerated stub
    }

}
