<?php
namespace App\Models;

use App\Models\base\CollectionBase;

class Suppliers extends CollectionBase {
    public function __construct()
    {
        parent::__construct("suppliers"); // TODO: Change the autogenerated stub
    }
}
