<?php
/**
 * Created by PhpStorm.
 * User: michael
 * Date: 4/23/15
 * Time: 16:37
 */

namespace App\Models;

use App\Models\base\CollectionBase;

class Teams extends CollectionBase {
    public function __construct()
    {
        parent::__construct("teams"); // TODO: Change the autogenerated stub
    }

}