<?php
namespace App\Models;

use App\Models\base\CollectionBase;

class Users extends CollectionBase {
    public function __construct()
    {
        parent::__construct("users"); // TODO: Change the autogenerated stub
    }

}
