<?php
namespace App\Models;

use App\Models\base\CollectionBase;

class Users extends CollectionBase {
    private static $instance;
    public static function getInstance()
    {
        if(self::$instance==null) {
            self::$instance=new Users();
        }
        return self::$instance;
    }

    public function __construct()
    {
        parent::__construct("users"); // TODO: Change the autogenerated stub
    }

}
